import { resolve } from '$app/paths';
import type { Component } from 'svelte';
import FlameIcon from '@lucide/svelte/icons/flame';
import MessageSquareIcon from '@lucide/svelte/icons/message-square';
import UserIcon from '@lucide/svelte/icons/user';
import SparklesIcon from '@lucide/svelte/icons/sparkles';
import SettingsIcon from '@lucide/svelte/icons/settings';
import BookmarkIcon from '@lucide/svelte/icons/bookmark';

export interface EmojiItem {
	emoji: string;
	name: string;
	tags: string[];
}

export type NavLink = {
	name: string;
	url: ResolvedUrl;
	icon: Component;
	colorClass?: string;
	headerText: string;
	headerDescription: string;
};

export const generalLinks: NavLink[] = [
	{
		name: 'Feed',
		url: resolve('/feed'),
		icon: FlameIcon,
		colorClass: 'text-orange-500 fill-orange-400',
		headerText: 'Your Feed',
		headerDescription: 'See what people are sharing and confessing.'
	},
	{
		name: 'Discover',
		url: resolve('/discover'),
		icon: SparklesIcon,
		colorClass: 'text-yellow-400',
		headerText: 'Discover',
		headerDescription: 'Explore new confessions and stories from people nearby.'
	},
	{
		name: 'Messages',
		url: resolve('/messages'),
		icon: MessageSquareIcon,
		colorClass: 'text-sky-500',
		headerText: 'Messages',
		headerDescription: 'Chat privately and connect with people you resonate with.'
	},
	{
		name: 'Profile',
		url: resolve('/profile'),
		icon: UserIcon,
		colorClass: 'text-emerald-500',
		headerText: 'Profile',
		headerDescription: 'View and personalize your profile, photos, and bio.'
	}
];

export const accountLinks: NavLink[] = [
	{
		name: 'Saved',
		url: resolve('/saved'),
		icon: BookmarkIcon,
		colorClass: 'text-yellow-500',
		headerText: 'Saved',
		headerDescription: 'Access the posts and confessions you’ve bookmarked.'
	},
	{
		name: 'Settings',
		url: resolve('/settings'),
		icon: SettingsIcon,
		colorClass: 'text-indigo-500',
		headerText: 'Settings',
		headerDescription: 'Adjust your preferences, privacy, and notifications.'
	}
];

export const emojis: EmojiItem[] = [
	{ emoji: '😀', name: 'grinning face', tags: ['happy', 'smile', 'joy', 'grin'] },
	{ emoji: '😃', name: 'grinning face with big eyes', tags: ['happy', 'smile', 'joy', 'excited'] },
	{
		emoji: '😄',
		name: 'grinning face with smiling eyes',
		tags: ['happy', 'smile', 'joy', 'laugh']
	},
	{ emoji: '😁', name: 'beaming face with smiling eyes', tags: ['happy', 'smile', 'joy', 'beam'] },
	{ emoji: '😆', name: 'grinning squinting face', tags: ['happy', 'laugh', 'joy', 'squint'] },
	{ emoji: '😅', name: 'grinning face with sweat', tags: ['happy', 'nervous', 'sweat', 'relief'] },
	{ emoji: '😂', name: 'face with tears of joy', tags: ['laugh', 'cry', 'tears', 'funny', 'lol'] },
	{
		emoji: '🤣',
		name: 'rolling on the floor laughing',
		tags: ['laugh', 'rofl', 'funny', 'hilarious']
	},
	{
		emoji: '😊',
		name: 'smiling face with smiling eyes',
		tags: ['happy', 'smile', 'blush', 'pleased']
	},
	{ emoji: '😇', name: 'smiling face with halo', tags: ['angel', 'innocent', 'good', 'holy'] },
	{ emoji: '🙂', name: 'slightly smiling face', tags: ['smile', 'happy', 'content'] },
	{ emoji: '🙃', name: 'upside-down face', tags: ['silly', 'sarcasm', 'irony', 'playful'] },
	{ emoji: '😉', name: 'winking face', tags: ['wink', 'flirt', 'playful', 'joke'] },
	{ emoji: '😌', name: 'relieved face', tags: ['relief', 'calm', 'peaceful', 'content'] },
	{ emoji: '😍', name: 'smiling face with heart-eyes', tags: ['love', 'heart', 'adore', 'crush'] },
	{ emoji: '🥰', name: 'smiling face with hearts', tags: ['love', 'affection', 'adore', 'hearts'] },
	{ emoji: '😘', name: 'face blowing a kiss', tags: ['kiss', 'love', 'romance', 'blow'] },
	{ emoji: '😗', name: 'kissing face', tags: ['kiss', 'love', 'romance', 'pucker'] },
	{
		emoji: '😙',
		name: 'kissing face with smiling eyes',
		tags: ['kiss', 'love', 'happy', 'romance']
	},
	{
		emoji: '😚',
		name: 'kissing face with closed eyes',
		tags: ['kiss', 'love', 'romance', 'peaceful']
	},
	{
		emoji: '😋',
		name: 'face savoring food',
		tags: ['yum', 'delicious', 'taste', 'food', 'tongue']
	},
	{ emoji: '😜', name: 'winking face with tongue', tags: ['playful', 'silly', 'tongue', 'wink'] },
	{ emoji: '🤪', name: 'zany face', tags: ['crazy', 'silly', 'wild', 'playful', 'tongue'] },
	{
		emoji: '😝',
		name: 'squinting face with tongue',
		tags: ['silly', 'playful', 'tongue', 'tease']
	},
	{ emoji: '🤑', name: 'money-mouth face', tags: ['money', 'rich', 'greedy', 'dollar'] },
	{
		emoji: '🤗',
		name: 'smiling face with open hands',
		tags: ['hug', 'embrace', 'welcome', 'friendly']
	},
	{ emoji: '🤭', name: 'face with hand over mouth', tags: ['oops', 'secret', 'whisper', 'giggle'] },
	{ emoji: '🤫', name: 'shushing face', tags: ['quiet', 'secret', 'shh', 'silence'] },
	{ emoji: '🤔', name: 'thinking face', tags: ['think', 'ponder', 'consider', 'hmm'] },
	{ emoji: '🤐', name: 'zipper-mouth face', tags: ['quiet', 'secret', 'sealed', 'zip'] },
	{
		emoji: '🤨',
		name: 'face with raised eyebrow',
		tags: ['suspicious', 'skeptical', 'questioning']
	},
	{ emoji: '😐', name: 'neutral face', tags: ['neutral', 'blank', 'meh', 'expressionless'] },
	{ emoji: '😑', name: 'expressionless face', tags: ['blank', 'neutral', 'deadpan', 'flat'] },
	{ emoji: '😶', name: 'face without mouth', tags: ['speechless', 'quiet', 'silent', 'no words'] },
	{ emoji: '😏', name: 'smirking face', tags: ['smirk', 'sly', 'confident', 'suggestive'] },
	{ emoji: '😒', name: 'unamused face', tags: ['annoyed', 'unimpressed', 'bored', 'meh'] },
	{
		emoji: '🙄',
		name: 'face with rolling eyes',
		tags: ['eye roll', 'annoyed', 'whatever', 'sarcastic']
	},
	{ emoji: '😬', name: 'grimacing face', tags: ['awkward', 'uncomfortable', 'oops', 'cringe'] },
	{ emoji: '🤥', name: 'lying face', tags: ['lie', 'dishonest', 'pinocchio', 'fib'] },
	{ emoji: '😔', name: 'pensive face', tags: ['sad', 'thoughtful', 'down', 'dejected'] },
	{ emoji: '😪', name: 'sleepy face', tags: ['tired', 'sleepy', 'exhausted', 'drowsy'] },
	{ emoji: '🤤', name: 'drooling face', tags: ['drool', 'desire', 'hungry', 'want'] },
	{ emoji: '😴', name: 'sleeping face', tags: ['sleep', 'tired', 'rest', 'zzz'] },
	{ emoji: '😷', name: 'face with medical mask', tags: ['sick', 'mask', 'medical', 'health'] },
	{ emoji: '🤒', name: 'face with thermometer', tags: ['sick', 'fever', 'ill', 'temperature'] },
	{ emoji: '🤕', name: 'face with head-bandage', tags: ['injured', 'hurt', 'bandage', 'ouch'] },
	{ emoji: '🤢', name: 'nauseated face', tags: ['sick', 'nausea', 'gross', 'disgusted'] },
	{ emoji: '🤮', name: 'face vomiting', tags: ['sick', 'vomit', 'throw up', 'ill'] },
	{ emoji: '🤧', name: 'sneezing face', tags: ['sneeze', 'sick', 'cold', 'achoo'] },
	{ emoji: '🥵', name: 'hot face', tags: ['hot', 'heat', 'sweat', 'burning'] },
	{ emoji: '🥶', name: 'cold face', tags: ['cold', 'freezing', 'frozen', 'chill'] },
	{ emoji: '🥴', name: 'woozy face', tags: ['dizzy', 'drunk', 'confused', 'disoriented'] },
	{
		emoji: '😵',
		name: 'face with crossed-out eyes',
		tags: ['dizzy', 'knocked out', 'dead', 'unconscious']
	},
	{ emoji: '🤯', name: 'exploding head', tags: ['mind blown', 'shocked', 'amazed', 'wow'] },
	{ emoji: '🤠', name: 'cowboy hat face', tags: ['cowboy', 'western', 'hat', 'yeehaw'] },
	{ emoji: '🥳', name: 'partying face', tags: ['party', 'celebration', 'birthday', 'fun'] },
	{
		emoji: '😎',
		name: 'smiling face with sunglasses',
		tags: ['cool', 'sunglasses', 'awesome', 'smooth']
	},
	{ emoji: '🤓', name: 'nerd face', tags: ['nerd', 'geek', 'smart', 'glasses', 'studious'] },
	{ emoji: '🧐', name: 'face with monocle', tags: ['fancy', 'curious', 'inspect', 'examine'] },
	{ emoji: '😕', name: 'confused face', tags: ['confused', 'puzzled', 'uncertain', 'hmm'] },
	{ emoji: '😟', name: 'worried face', tags: ['worried', 'anxious', 'concerned', 'trouble'] },
	{ emoji: '🙁', name: 'slightly frowning face', tags: ['sad', 'disappointed', 'frown', 'down'] },
	{ emoji: '☹️', name: 'frowning face', tags: ['sad', 'unhappy', 'frown', 'disappointed'] },
	{ emoji: '😮', name: 'face with open mouth', tags: ['surprised', 'shocked', 'wow', 'amazed'] },
	{ emoji: '😯', name: 'hushed face', tags: ['surprised', 'quiet', 'amazed', 'speechless'] },
	{ emoji: '😲', name: 'astonished face', tags: ['shocked', 'surprised', 'amazed', 'wow'] },
	{ emoji: '😳', name: 'flushed face', tags: ['embarrassed', 'shy', 'blushing', 'awkward'] },
	{ emoji: '🥺', name: 'pleading face', tags: ['puppy eyes', 'cute', 'beg', 'please'] },
	{ emoji: '😦', name: 'frowning face with open mouth', tags: ['sad', 'disappointed', 'upset'] },
	{ emoji: '😧', name: 'anguished face', tags: ['anguish', 'pain', 'distress', 'suffering'] },
	{ emoji: '😨', name: 'fearful face', tags: ['scared', 'afraid', 'fear', 'frightened'] },
	{
		emoji: '😰',
		name: 'anxious face with sweat',
		tags: ['anxious', 'nervous', 'worried', 'sweat']
	},
	{ emoji: '😥', name: 'sad but relieved face', tags: ['sad', 'relief', 'disappointed', 'sigh'] },
	{ emoji: '😢', name: 'crying face', tags: ['cry', 'sad', 'tears', 'upset'] },
	{ emoji: '😭', name: 'loudly crying face', tags: ['crying', 'sob', 'tears', 'wail'] },
	{ emoji: '😱', name: 'face screaming in fear', tags: ['scream', 'scared', 'horror', 'shock'] },
	{ emoji: '😖', name: 'confounded face', tags: ['frustrated', 'confused', 'annoyed', 'upset'] },
	{ emoji: '😣', name: 'persevering face', tags: ['struggle', 'effort', 'persevere', 'strain'] },
	{ emoji: '😞', name: 'disappointed face', tags: ['disappointed', 'sad', 'let down', 'dejected'] },
	{
		emoji: '😓',
		name: 'downcast face with sweat',
		tags: ['tired', 'exhausted', 'disappointed', 'sweat']
	},
	{ emoji: '😩', name: 'weary face', tags: ['tired', 'exhausted', 'fed up', 'weary'] },
	{ emoji: '😫', name: 'tired face', tags: ['tired', 'exhausted', 'frustrated', 'done'] },
	{ emoji: '🥱', name: 'yawning face', tags: ['yawn', 'tired', 'sleepy', 'bored'] },
	{
		emoji: '😤',
		name: 'face with steam from nose',
		tags: ['frustrated', 'angry', 'steaming', 'huffing']
	},
	{ emoji: '😡', name: 'enraged face', tags: ['angry', 'mad', 'furious', 'rage'] },
	{ emoji: '😠', name: 'angry face', tags: ['angry', 'mad', 'upset', 'grumpy'] },
	{
		emoji: '🤬',
		name: 'face with symbols on mouth',
		tags: ['swearing', 'cursing', 'angry', 'profanity']
	},
	{
		emoji: '😈',
		name: 'smiling face with horns',
		tags: ['devil', 'evil', 'mischievous', 'naughty']
	},
	{ emoji: '👿', name: 'angry face with horns', tags: ['devil', 'evil', 'angry', 'demon'] },
	{ emoji: '💀', name: 'skull', tags: ['death', 'dead', 'skeleton', 'bone'] },
	{ emoji: '☠️', name: 'skull and crossbones', tags: ['death', 'danger', 'poison', 'pirate'] },
	{ emoji: '💩', name: 'pile of poo', tags: ['poop', 'shit', 'crap', 'funny'] },
	{ emoji: '🤡', name: 'clown face', tags: ['clown', 'circus', 'funny', 'joke'] },
	{ emoji: '👹', name: 'ogre', tags: ['monster', 'demon', 'scary', 'ogre'] },
	{ emoji: '👺', name: 'goblin', tags: ['monster', 'demon', 'scary', 'goblin'] },
	{ emoji: '👻', name: 'ghost', tags: ['ghost', 'spooky', 'halloween', 'spirit'] },
	{ emoji: '👽', name: 'alien', tags: ['alien', 'ufo', 'extraterrestrial', 'space'] },
	{ emoji: '👾', name: 'alien monster', tags: ['alien', 'monster', 'video game', 'pixel'] },
	{ emoji: '🤖', name: 'robot', tags: ['robot', 'ai', 'artificial', 'machine'] },
	{ emoji: '😺', name: 'grinning cat', tags: ['cat', 'happy', 'smile', 'pet'] },
	{ emoji: '😸', name: 'grinning cat with smiling eyes', tags: ['cat', 'happy', 'laugh', 'pet'] },
	{ emoji: '😹', name: 'cat with tears of joy', tags: ['cat', 'laugh', 'funny', 'pet'] },
	{ emoji: '😻', name: 'smiling cat with heart-eyes', tags: ['cat', 'love', 'heart', 'pet'] },
	{ emoji: '😼', name: 'cat with wry smile', tags: ['cat', 'smirk', 'sly', 'pet'] },
	{ emoji: '😽', name: 'kissing cat', tags: ['cat', 'kiss', 'love', 'pet'] },
	{ emoji: '🙀', name: 'weary cat', tags: ['cat', 'scared', 'shocked', 'pet'] },
	{ emoji: '😿', name: 'crying cat', tags: ['cat', 'sad', 'cry', 'pet'] },
	{ emoji: '😾', name: 'pouting cat', tags: ['cat', 'angry', 'grumpy', 'pet'] },
	{ emoji: '💋', name: 'kiss mark', tags: ['kiss', 'lips', 'love', 'romance'] },
	{ emoji: '💌', name: 'love letter', tags: ['love', 'letter', 'romance', 'mail'] },
	{ emoji: '💘', name: 'heart with arrow', tags: ['love', 'cupid', 'romance', 'arrow'] },
	{ emoji: '💝', name: 'heart with ribbon', tags: ['love', 'gift', 'present', 'heart'] },
	{ emoji: '💖', name: 'sparkling heart', tags: ['love', 'sparkle', 'heart', 'romance'] },
	{ emoji: '💗', name: 'growing heart', tags: ['love', 'growing', 'heart', 'romance'] },
	{ emoji: '💓', name: 'beating heart', tags: ['love', 'beating', 'heart', 'pulse'] },
	{ emoji: '💞', name: 'revolving hearts', tags: ['love', 'hearts', 'romance', 'revolving'] },
	{ emoji: '💕', name: 'two hearts', tags: ['love', 'hearts', 'romance', 'two'] },
	{ emoji: '💟', name: 'heart decoration', tags: ['love', 'heart', 'decoration', 'purple'] },
	{ emoji: '❣️', name: 'heart exclamation', tags: ['love', 'heart', 'exclamation', 'emphasis'] },
	{ emoji: '💔', name: 'broken heart', tags: ['broken', 'heart', 'sad', 'breakup'] },
	{ emoji: '❤️', name: 'red heart', tags: ['love', 'heart', 'red', 'romance'] },
	{ emoji: '🧡', name: 'orange heart', tags: ['love', 'heart', 'orange', 'friendship'] },
	{ emoji: '💛', name: 'yellow heart', tags: ['love', 'heart', 'yellow', 'friendship'] },
	{ emoji: '💚', name: 'green heart', tags: ['love', 'heart', 'green', 'nature'] },
	{ emoji: '💙', name: 'blue heart', tags: ['love', 'heart', 'blue', 'trust'] },
	{ emoji: '💜', name: 'purple heart', tags: ['love', 'heart', 'purple', 'compassion'] },
	{ emoji: '🤎', name: 'brown heart', tags: ['love', 'heart', 'brown', 'earth'] },
	{ emoji: '🖤', name: 'black heart', tags: ['love', 'heart', 'black', 'dark'] },
	{ emoji: '🤍', name: 'white heart', tags: ['love', 'heart', 'white', 'pure'] },
	{ emoji: '💯', name: 'hundred points', tags: ['100', 'perfect', 'score', 'excellent'] },
	{ emoji: '💢', name: 'anger symbol', tags: ['angry', 'symbol', 'mad', 'frustration'] },
	{ emoji: '💥', name: 'collision', tags: ['explosion', 'boom', 'crash', 'impact'] },
	{ emoji: '💫', name: 'dizzy', tags: ['dizzy', 'stars', 'sparkle', 'confused'] },
	{ emoji: '💦', name: 'sweat droplets', tags: ['sweat', 'water', 'droplets', 'exercise'] },
	{ emoji: '💨', name: 'dashing away', tags: ['fast', 'speed', 'wind', 'dash'] },
	{ emoji: '🕳️', name: 'hole', tags: ['hole', 'empty', 'void', 'pit'] },
	{ emoji: '💬', name: 'speech balloon', tags: ['speech', 'talk', 'chat', 'conversation'] },
	{ emoji: '👋', name: 'waving hand', tags: ['wave', 'hello', 'goodbye', 'hi'] },
	{ emoji: '🤚', name: 'raised back of hand', tags: ['hand', 'stop', 'high five', 'palm'] },
	{ emoji: '🖐️', name: 'hand with fingers splayed', tags: ['hand', 'five', 'stop', 'palm'] },
	{ emoji: '✋', name: 'raised hand', tags: ['hand', 'stop', 'high five', 'palm'] },
	{ emoji: '🖖', name: 'vulcan salute', tags: ['spock', 'vulcan', 'star trek', 'peace'] },
	{ emoji: '👌', name: 'ok hand', tags: ['ok', 'okay', 'perfect', 'good'] },
	{ emoji: '🤌', name: 'pinched fingers', tags: ['italian', 'gesture', 'chef kiss', 'perfect'] },
	{ emoji: '🤏', name: 'pinching hand', tags: ['small', 'tiny', 'little', 'pinch'] },
	{ emoji: '✌️', name: 'victory hand', tags: ['peace', 'victory', 'two', 'v'] },
	{ emoji: '🤞', name: 'crossed fingers', tags: ['luck', 'hope', 'wish', 'cross'] },
	{ emoji: '🤟', name: 'love-you gesture', tags: ['love', 'you', 'sign language', 'ily'] },
	{ emoji: '🤘', name: 'sign of the horns', tags: ['rock', 'metal', 'horns', 'cool'] },
	{ emoji: '🤙', name: 'call me hand', tags: ['call', 'phone', 'shaka', 'hang loose'] },
	{
		emoji: '👈',
		name: 'backhand index pointing left',
		tags: ['point', 'left', 'direction', 'finger']
	},
	{
		emoji: '👉',
		name: 'backhand index pointing right',
		tags: ['point', 'right', 'direction', 'finger']
	},
	{ emoji: '👆', name: 'backhand index pointing up', tags: ['point', 'up', 'direction', 'finger'] },
	{
		emoji: '👇',
		name: 'backhand index pointing down',
		tags: ['point', 'down', 'direction', 'finger']
	},
	{ emoji: '👍', name: 'thumbs up', tags: ['thumbs up', 'good', 'like', 'yes'] },
	{ emoji: '👎', name: 'thumbs down', tags: ['thumbs down', 'bad', 'dislike', 'no'] },
	{ emoji: '✊', name: 'raised fist', tags: ['fist', 'power', 'strength', 'solidarity'] },
	{ emoji: '👊', name: 'oncoming fist', tags: ['fist', 'punch', 'bump', 'knuckle'] },
	{ emoji: '🤛', name: 'left-facing fist', tags: ['fist', 'bump', 'left', 'punch'] },
	{ emoji: '🤜', name: 'right-facing fist', tags: ['fist', 'bump', 'right', 'punch'] },
	{ emoji: '👏', name: 'clapping hands', tags: ['clap', 'applause', 'praise', 'good job'] },
	{ emoji: '🙌', name: 'raising hands', tags: ['praise', 'celebration', 'hooray', 'hands up'] },
	{ emoji: '🫶', name: 'heart hands', tags: ['love', 'heart', 'hands', 'care'] },
	{ emoji: '👐', name: 'open hands', tags: ['hands', 'open', 'hug', 'embrace'] },
	{ emoji: '🤲', name: 'palms up together', tags: ['pray', 'please', 'beg', 'hope'] },
	{ emoji: '🙏', name: 'folded hands', tags: ['pray', 'thank you', 'please', 'namaste'] },
	{ emoji: '🤝', name: 'handshake', tags: ['handshake', 'deal', 'agreement', 'meet'] },
	{ emoji: '💅', name: 'nail polish', tags: ['nails', 'beauty', 'polish', 'manicure'] },
	{ emoji: '👣', name: 'footprints', tags: ['feet', 'footprints', 'steps', 'walk'] },
	{ emoji: '👀', name: 'eyes', tags: ['eyes', 'look', 'see', 'watch'] },
	{ emoji: '👁️', name: 'eye', tags: ['eye', 'see', 'look', 'vision'] },
	{ emoji: '🧠', name: 'brain', tags: ['brain', 'smart', 'think', 'mind'] },
	{ emoji: '👅', name: 'tongue', tags: ['tongue', 'taste', 'lick', 'mouth'] },
	{ emoji: '👄', name: 'mouth', tags: ['mouth', 'lips', 'kiss', 'talk'] },
	{ emoji: '🫦', name: 'biting lip', tags: ['lip', 'bite', 'nervous', 'flirt'] },
	{ emoji: '👶', name: 'baby', tags: ['baby', 'infant', 'child', 'young'] },
	{ emoji: '🧒', name: 'child', tags: ['child', 'kid', 'young', 'person'] },
	{ emoji: '👦', name: 'boy', tags: ['boy', 'male', 'child', 'son'] },
	{ emoji: '👧', name: 'girl', tags: ['girl', 'female', 'child', 'daughter'] },
	{ emoji: '🧑', name: 'person', tags: ['person', 'adult', 'human', 'individual'] },
	{ emoji: '👨', name: 'man', tags: ['man', 'male', 'adult', 'guy'] },
	{ emoji: '👩', name: 'woman', tags: ['woman', 'female', 'adult', 'lady'] },
	{ emoji: '🧓', name: 'older person', tags: ['old', 'elderly', 'senior', 'aged'] },
	{ emoji: '👴', name: 'old man', tags: ['old', 'man', 'elderly', 'grandfather'] },
	{ emoji: '👵', name: 'old woman', tags: ['old', 'woman', 'elderly', 'grandmother'] },
	{ emoji: '🙍', name: 'person frowning', tags: ['frown', 'sad', 'unhappy', 'disappointed'] },
	{ emoji: '🙎', name: 'person pouting', tags: ['pout', 'sulk', 'grumpy', 'upset'] },
	{ emoji: '🙅', name: 'person gesturing no', tags: ['no', 'stop', 'refuse', 'deny'] },
	{ emoji: '🙆', name: 'person gesturing ok', tags: ['ok', 'yes', 'good', 'approve'] },
	{ emoji: '💁', name: 'person tipping hand', tags: ['help', 'information', 'sass', 'tip'] },
	{ emoji: '🙋', name: 'person raising hand', tags: ['raise hand', 'question', 'volunteer', 'me'] },
	{ emoji: '🧏', name: 'deaf person', tags: ['deaf', 'hearing', 'disability', 'sign'] },
	{ emoji: '🙇', name: 'person bowing', tags: ['bow', 'respect', 'sorry', 'thank you'] },
	{ emoji: '🤦', name: 'person facepalming', tags: ['facepalm', 'frustrated', 'doh', 'mistake'] },
	{ emoji: '🤷', name: 'person shrugging', tags: ['shrug', 'dunno', 'whatever', 'idk'] },
	{ emoji: '👮', name: 'police officer', tags: ['police', 'cop', 'officer', 'law'] },
	{ emoji: '🕵️', name: 'detective', tags: ['detective', 'spy', 'investigate', 'sleuth'] },
	{ emoji: '💂', name: 'guard', tags: ['guard', 'soldier', 'protect', 'british'] },
	{ emoji: '🥷', name: 'ninja', tags: ['ninja', 'stealth', 'martial arts', 'hidden'] },
	{
		emoji: '👷',
		name: 'construction worker',
		tags: ['construction', 'worker', 'build', 'hard hat']
	},
	{ emoji: '🤴', name: 'prince', tags: ['prince', 'royal', 'crown', 'nobility'] },
	{ emoji: '👸', name: 'princess', tags: ['princess', 'royal', 'crown', 'nobility'] },
	{ emoji: '👳', name: 'person wearing turban', tags: ['turban', 'head wrap', 'religion', 'sikh'] },
	{ emoji: '👲', name: 'person with skullcap', tags: ['hat', 'cap', 'chinese', 'traditional'] },
	{ emoji: '🧕', name: 'woman with headscarf', tags: ['hijab', 'headscarf', 'muslim', 'religion'] },
	{ emoji: '🧔', name: 'person with beard', tags: ['beard', 'facial hair', 'man', 'hairy'] },
	{ emoji: '👱', name: 'person with blond hair', tags: ['blond', 'blonde', 'hair', 'light'] },
	{ emoji: '👨‍🦰', name: 'man with red hair', tags: ['man', 'red hair', 'ginger', 'redhead'] },
	{ emoji: '👩‍🦰', name: 'woman with red hair', tags: ['woman', 'red hair', 'ginger', 'redhead'] },
	{ emoji: '👨‍🦱', name: 'man with curly hair', tags: ['man', 'curly hair', 'curls', 'wavy'] },
	{ emoji: '👩‍🦱', name: 'woman with curly hair', tags: ['woman', 'curly hair', 'curls', 'wavy'] },
	{ emoji: '👨‍🦳', name: 'man with white hair', tags: ['man', 'white hair', 'gray', 'old'] },
	{ emoji: '👩‍🦳', name: 'woman with white hair', tags: ['woman', 'white hair', 'gray', 'old'] },
	{ emoji: '👨‍🦲', name: 'man with no hair', tags: ['man', 'bald', 'no hair', 'hairless'] },
	{ emoji: '👩‍🦲', name: 'woman with no hair', tags: ['woman', 'bald', 'no hair', 'hairless'] },
	{ emoji: '🧑‍⚕️', name: 'health worker', tags: ['doctor', 'nurse', 'medical', 'health'] },
	{ emoji: '👨‍⚕️', name: 'man health worker', tags: ['doctor', 'man', 'medical', 'health'] },
	{ emoji: '👩‍⚕️', name: 'woman health worker', tags: ['doctor', 'woman', 'medical', 'health'] },
	{ emoji: '🧑‍🎓', name: 'student', tags: ['student', 'graduate', 'education', 'school'] },
	{ emoji: '👨‍🎓', name: 'man student', tags: ['student', 'man', 'graduate', 'education'] },
	{ emoji: '👩‍🎓', name: 'woman student', tags: ['student', 'woman', 'graduate', 'education'] },
	{ emoji: '🧑‍🏫', name: 'teacher', tags: ['teacher', 'educator', 'school', 'teach'] },
	{ emoji: '👨‍🏫', name: 'man teacher', tags: ['teacher', 'man', 'educator', 'school'] },
	{ emoji: '👩‍🏫', name: 'woman teacher', tags: ['teacher', 'woman', 'educator', 'school'] },
	{ emoji: '🧑‍⚖️', name: 'judge', tags: ['judge', 'law', 'court', 'justice'] },
	{ emoji: '👨‍⚖️', name: 'man judge', tags: ['judge', 'man', 'law', 'court'] },
	{ emoji: '👩‍⚖️', name: 'woman judge', tags: ['judge', 'woman', 'law', 'court'] },
	{ emoji: '🧑‍🌾', name: 'farmer', tags: ['farmer', 'agriculture', 'farm', 'crops'] },
	{ emoji: '👨‍🌾', name: 'man farmer', tags: ['farmer', 'man', 'agriculture', 'farm'] },
	{ emoji: '👩‍🌾', name: 'woman farmer', tags: ['farmer', 'woman', 'agriculture', 'farm'] },
	{ emoji: '🧑‍🍳', name: 'cook', tags: ['chef', 'cook', 'kitchen', 'food'] },
	{ emoji: '👨‍🍳', name: 'man cook', tags: ['chef', 'man', 'cook', 'kitchen'] },
	{ emoji: '👩‍🍳', name: 'woman cook', tags: ['chef', 'woman', 'cook', 'kitchen'] },
	{ emoji: '🧑‍🔧', name: 'mechanic', tags: ['mechanic', 'repair', 'fix', 'tools'] },
	{ emoji: '👨‍🔧', name: 'man mechanic', tags: ['mechanic', 'man', 'repair', 'fix'] },
	{ emoji: '👩‍🔧', name: 'woman mechanic', tags: ['mechanic', 'woman', 'repair', 'fix'] },
	{ emoji: '🧑‍🏭', name: 'factory worker', tags: ['factory', 'worker', 'industry', 'manufacturing'] },
	{ emoji: '👨‍🏭', name: 'man factory worker', tags: ['factory', 'man', 'worker', 'industry'] },
	{ emoji: '👩‍🏭', name: 'woman factory worker', tags: ['factory', 'woman', 'worker', 'industry'] },
	{ emoji: '🧑‍💼', name: 'office worker', tags: ['office', 'business', 'work', 'professional'] },
	{ emoji: '👨‍💼', name: 'man office worker', tags: ['office', 'man', 'business', 'work'] },
	{ emoji: '👩‍💼', name: 'woman office worker', tags: ['office', 'woman', 'business', 'work'] },
	{ emoji: '🧑‍🔬', name: 'scientist', tags: ['scientist', 'research', 'lab', 'science'] },
	{ emoji: '👨‍🔬', name: 'man scientist', tags: ['scientist', 'man', 'research', 'lab'] },
	{ emoji: '👩‍🔬', name: 'woman scientist', tags: ['scientist', 'woman', 'research', 'lab'] },
	{ emoji: '🧑‍💻', name: 'technologist', tags: ['programmer', 'developer', 'computer', 'tech'] },
	{ emoji: '👨‍💻', name: 'man technologist', tags: ['programmer', 'man', 'developer', 'computer'] },
	{
		emoji: '👩‍💻',
		name: 'woman technologist',
		tags: ['programmer', 'woman', 'developer', 'computer']
	},
	{ emoji: '🧑‍🎤', name: 'singer', tags: ['singer', 'music', 'microphone', 'perform'] },
	{ emoji: '👨‍🎤', name: 'man singer', tags: ['singer', 'man', 'music', 'microphone'] },
	{ emoji: '👩‍🎤', name: 'woman singer', tags: ['singer', 'woman', 'music', 'microphone'] },
	{ emoji: '🧑‍🎨', name: 'artist', tags: ['artist', 'paint', 'creative', 'art'] },
	{ emoji: '👨‍🎨', name: 'man artist', tags: ['artist', 'man', 'paint', 'creative'] },
	{ emoji: '👩‍🎨', name: 'woman artist', tags: ['artist', 'woman', 'paint', 'creative'] },
	{ emoji: '🧑‍✈️', name: 'pilot', tags: ['pilot', 'airplane', 'fly', 'aviation'] },
	{ emoji: '👨‍✈️', name: 'man pilot', tags: ['pilot', 'man', 'airplane', 'fly'] },
	{ emoji: '👩‍✈️', name: 'woman pilot', tags: ['pilot', 'woman', 'airplane', 'fly'] },
	{ emoji: '🧑‍🚀', name: 'astronaut', tags: ['astronaut', 'space', 'rocket', 'cosmos'] },
	{ emoji: '👨‍🚀', name: 'man astronaut', tags: ['astronaut', 'man', 'space', 'rocket'] },
	{ emoji: '👩‍🚀', name: 'woman astronaut', tags: ['astronaut', 'woman', 'space', 'rocket'] },
	{ emoji: '🧑‍🚒', name: 'firefighter', tags: ['firefighter', 'fire', 'rescue', 'hero'] },
	{ emoji: '👨‍🚒', name: 'man firefighter', tags: ['firefighter', 'man', 'fire', 'rescue'] },
	{ emoji: '👩‍🚒', name: 'woman firefighter', tags: ['firefighter', 'woman', 'fire', 'rescue'] },
	{ emoji: '👮‍♂️', name: 'man police officer', tags: ['police', 'man', 'cop', 'officer'] },
	{ emoji: '👮‍♀️', name: 'woman police officer', tags: ['police', 'woman', 'cop', 'officer'] },
	{ emoji: '🕵️‍♂️', name: 'man detective', tags: ['detective', 'man', 'spy', 'investigate'] },
	{ emoji: '🕵️‍♀️', name: 'woman detective', tags: ['detective', 'woman', 'spy', 'investigate'] },
	{ emoji: '💃', name: 'woman dancing', tags: ['dance', 'woman', 'party', 'celebration'] },
	{ emoji: '🕺', name: 'man dancing', tags: ['dance', 'man', 'party', 'celebration'] },
	{
		emoji: '🕴️',
		name: 'person in suit levitating',
		tags: ['levitate', 'suit', 'business', 'floating']
	},
	{ emoji: '👯', name: 'people with bunny ears', tags: ['party', 'bunny', 'celebration', 'dance'] },
	{ emoji: '🧍', name: 'person standing', tags: ['standing', 'upright', 'person', 'still'] },
	{ emoji: '🧎', name: 'person kneeling', tags: ['kneeling', 'kneel', 'prayer', 'respect'] },
	{ emoji: '🧑‍🤝‍🧑', name: 'people holding hands', tags: ['friends', 'together', 'unity', 'support'] },
	{
		emoji: '👫',
		name: 'woman and man holding hands',
		tags: ['couple', 'together', 'relationship', 'love']
	},
	{
		emoji: '👭',
		name: 'women holding hands',
		tags: ['friends', 'women', 'together', 'friendship']
	},
	{ emoji: '👬', name: 'men holding hands', tags: ['friends', 'men', 'together', 'friendship'] },
	{ emoji: '💏', name: 'kiss', tags: ['kiss', 'love', 'romance', 'couple'] },
	{ emoji: '💑', name: 'couple with heart', tags: ['couple', 'love', 'heart', 'romance'] },
	{ emoji: '👪', name: 'family', tags: ['family', 'parents', 'children', 'home'] },
	{ emoji: '🧸', name: 'teddy bear', tags: ['bear', 'toy', 'cute', 'childhood'] },
	{ emoji: '🎈', name: 'balloon', tags: ['balloon', 'party', 'celebration', 'float'] },
	{ emoji: '🎉', name: 'party popper', tags: ['party', 'celebration', 'confetti', 'fun'] },
	{ emoji: '🎊', name: 'confetti ball', tags: ['confetti', 'celebration', 'party', 'festive'] },
	{ emoji: '🎁', name: 'wrapped gift', tags: ['gift', 'present', 'birthday', 'surprise'] },
	{ emoji: '🎂', name: 'birthday cake', tags: ['cake', 'birthday', 'celebration', 'candles'] },
	{ emoji: '🍰', name: 'shortcake', tags: ['cake', 'dessert', 'sweet', 'strawberry'] },
	{ emoji: '🧁', name: 'cupcake', tags: ['cupcake', 'dessert', 'sweet', 'frosting'] },
	{ emoji: '🍫', name: 'chocolate bar', tags: ['chocolate', 'candy', 'sweet', 'dessert'] },
	{ emoji: '🍩', name: 'doughnut', tags: ['donut', 'sweet', 'dessert', 'pastry'] },
	{ emoji: '🍪', name: 'cookie', tags: ['cookie', 'sweet', 'dessert', 'baked'] },
	{ emoji: '🍿', name: 'popcorn', tags: ['popcorn', 'movie', 'snack', 'cinema'] },
	{ emoji: '🍎', name: 'red apple', tags: ['apple', 'fruit', 'healthy', 'red'] },
	{ emoji: '🍇', name: 'grapes', tags: ['grapes', 'fruit', 'wine', 'purple'] },
	{ emoji: '🍉', name: 'watermelon', tags: ['watermelon', 'fruit', 'summer', 'refreshing'] },
	{ emoji: '🍒', name: 'cherries', tags: ['cherry', 'fruit', 'red', 'sweet'] },
	{ emoji: '🥭', name: 'mango', tags: ['mango', 'fruit', 'tropical', 'sweet'] },
	{ emoji: '🍍', name: 'pineapple', tags: ['pineapple', 'fruit', 'tropical', 'sweet'] },
	{ emoji: '🍕', name: 'pizza', tags: ['pizza', 'food', 'italian', 'cheese'] },
	{ emoji: '🍔', name: 'hamburger', tags: ['burger', 'food', 'fast food', 'meat'] },
	{ emoji: '🍟', name: 'french fries', tags: ['fries', 'food', 'fast food', 'potato'] },
	{ emoji: '🍝', name: 'spaghetti', tags: ['pasta', 'italian', 'food', 'noodles'] },
	{ emoji: '🌮', name: 'taco', tags: ['taco', 'mexican', 'food', 'spicy'] },
	{ emoji: '🌯', name: 'burrito', tags: ['burrito', 'mexican', 'food', 'wrap'] },
	{ emoji: '🥗', name: 'green salad', tags: ['salad', 'healthy', 'vegetables', 'green'] },
	{ emoji: '🍜', name: 'steaming bowl', tags: ['soup', 'ramen', 'noodles', 'hot'] },
	{ emoji: '🍣', name: 'sushi', tags: ['sushi', 'japanese', 'fish', 'raw'] },
	{ emoji: '🥟', name: 'dumpling', tags: ['dumpling', 'food', 'asian', 'steamed'] },
	{ emoji: '🥪', name: 'sandwich', tags: ['sandwich', 'food', 'bread', 'lunch'] },
	{ emoji: '☕', name: 'hot beverage', tags: ['coffee', 'tea', 'hot', 'drink'] },
	{ emoji: '🍵', name: 'teacup without handle', tags: ['tea', 'green tea', 'hot', 'drink'] },
	{ emoji: '🍺', name: 'beer mug', tags: ['beer', 'alcohol', 'drink', 'mug'] },
	{ emoji: '🍷', name: 'wine glass', tags: ['wine', 'alcohol', 'drink', 'red'] },
	{ emoji: '🍸', name: 'cocktail glass', tags: ['cocktail', 'martini', 'alcohol', 'drink'] },
	{ emoji: '🍹', name: 'tropical drink', tags: ['tropical', 'cocktail', 'drink', 'vacation'] },
	{ emoji: '🍶', name: 'sake', tags: ['sake', 'japanese', 'alcohol', 'rice wine'] },
	{ emoji: '🥂', name: 'clinking glasses', tags: ['cheers', 'toast', 'celebration', 'champagne'] },
	{
		emoji: '🍾',
		name: 'bottle with popping cork',
		tags: ['champagne', 'celebration', 'party', 'cork']
	},
	{ emoji: '🥤', name: 'cup with straw', tags: ['drink', 'soda', 'straw', 'cup'] },
	{ emoji: '🚗', name: 'automobile', tags: ['car', 'vehicle', 'drive', 'transport'] },
	{ emoji: '🚕', name: 'taxi', tags: ['taxi', 'cab', 'yellow', 'transport'] },
	{ emoji: '🚙', name: 'sport utility vehicle', tags: ['suv', 'car', 'vehicle', 'big'] },
	{ emoji: '🚌', name: 'bus', tags: ['bus', 'public transport', 'vehicle', 'group'] },
	{ emoji: '🚎', name: 'trolleybus', tags: ['trolley', 'bus', 'electric', 'transport'] },
	{ emoji: '🏎️', name: 'racing car', tags: ['race car', 'fast', 'speed', 'formula'] },
	{ emoji: '🚓', name: 'police car', tags: ['police', 'cop', 'law', 'emergency'] },
	{ emoji: '🚑', name: 'ambulance', tags: ['ambulance', 'medical', 'emergency', 'hospital'] },
	{ emoji: '🚒', name: 'fire engine', tags: ['fire truck', 'emergency', 'firefighter', 'red'] },
	{ emoji: '🚐', name: 'minibus', tags: ['van', 'minibus', 'transport', 'family'] },
	{ emoji: '🚚', name: 'delivery truck', tags: ['truck', 'delivery', 'transport', 'cargo'] },
	{ emoji: '🚛', name: 'articulated lorry', tags: ['truck', 'semi', 'transport', 'big'] },
	{ emoji: '🚜', name: 'tractor', tags: ['tractor', 'farm', 'agriculture', 'farming'] },
	{ emoji: '✈️', name: 'airplane', tags: ['airplane', 'plane', 'fly', 'travel'] },
	{ emoji: '🚀', name: 'rocket', tags: ['rocket', 'space', 'launch', 'fast'] },
	{ emoji: '🛸', name: 'flying saucer', tags: ['ufo', 'alien', 'spaceship', 'extraterrestrial'] },
	{ emoji: '🚁', name: 'helicopter', tags: ['helicopter', 'chopper', 'fly', 'rotor'] },
	{ emoji: '⛵', name: 'sailboat', tags: ['boat', 'sail', 'water', 'ocean'] },
	{ emoji: '🛶', name: 'canoe', tags: ['canoe', 'boat', 'paddle', 'water'] },
	{ emoji: '🚤', name: 'speedboat', tags: ['speedboat', 'fast', 'water', 'boat'] },
	{ emoji: '🛥️', name: 'motor boat', tags: ['yacht', 'boat', 'luxury', 'water'] },
	{ emoji: '⚓', name: 'anchor', tags: ['anchor', 'ship', 'boat', 'heavy'] },
	{ emoji: '🏠', name: 'house', tags: ['house', 'home', 'building', 'family'] },
	{ emoji: '🏡', name: 'house with garden', tags: ['house', 'home', 'garden', 'suburban'] },
	{ emoji: '🏢', name: 'office building', tags: ['office', 'building', 'work', 'business'] },
	{ emoji: '🏬', name: 'department store', tags: ['store', 'shopping', 'mall', 'retail'] },
	{ emoji: '🏫', name: 'school', tags: ['school', 'education', 'learning', 'students'] },
	{ emoji: '🏥', name: 'hospital', tags: ['hospital', 'medical', 'health', 'doctor'] },
	{ emoji: '🏦', name: 'bank', tags: ['bank', 'money', 'finance', 'building'] },
	{
		emoji: '🏛️',
		name: 'classical building',
		tags: ['government', 'museum', 'classical', 'columns']
	},
	{ emoji: '🕌', name: 'mosque', tags: ['mosque', 'religion', 'islam', 'worship'] },
	{ emoji: '⛩️', name: 'shinto shrine', tags: ['shrine', 'japan', 'shinto', 'religion'] },
	{ emoji: '🏰', name: 'castle', tags: ['castle', 'fortress', 'medieval', 'royal'] },
	{ emoji: '🌋', name: 'volcano', tags: ['volcano', 'mountain', 'eruption', 'lava'] },
	{ emoji: '🗻', name: 'mount fuji', tags: ['mountain', 'fuji', 'japan', 'peak'] },
	{ emoji: '🏞️', name: 'national park', tags: ['park', 'nature', 'scenery', 'landscape'] },
	{ emoji: '🌅', name: 'sunrise', tags: ['sunrise', 'morning', 'dawn', 'sun'] },
	{ emoji: '🌄', name: 'sunrise over mountains', tags: ['sunrise', 'mountain', 'dawn', 'scenic'] },
	{ emoji: '🌠', name: 'shooting star', tags: ['star', 'meteor', 'wish', 'night'] },
	{ emoji: '🎆', name: 'fireworks', tags: ['fireworks', 'celebration', 'party', 'explosion'] },
	{ emoji: '🎇', name: 'sparkler', tags: ['sparkler', 'celebration', 'party', 'handheld'] },
	{ emoji: '🌇', name: 'sunset', tags: ['sunset', 'evening', 'dusk', 'city'] },
	{ emoji: '🌃', name: 'night with stars', tags: ['night', 'city', 'stars', 'urban'] },
	{ emoji: '🌈', name: 'rainbow', tags: ['rainbow', 'colorful', 'weather', 'pride'] },
	{ emoji: '☀️', name: 'sun', tags: ['sun', 'sunny', 'bright', 'hot'] },
	{
		emoji: '🌤️',
		name: 'sun behind small cloud',
		tags: ['partly cloudy', 'sun', 'cloud', 'weather']
	},
	{ emoji: '🌥️', name: 'sun behind large cloud', tags: ['cloudy', 'overcast', 'weather', 'gray'] },
	{ emoji: '🌦️', name: 'sun behind rain cloud', tags: ['rain', 'shower', 'weather', 'mixed'] },
	{ emoji: '🌧️', name: 'cloud with rain', tags: ['rain', 'wet', 'storm', 'weather'] },
	{
		emoji: '⛈️',
		name: 'cloud with lightning and rain',
		tags: ['thunderstorm', 'lightning', 'storm', 'weather']
	},
	{
		emoji: '🌩️',
		name: 'cloud with lightning',
		tags: ['lightning', 'thunder', 'storm', 'electric']
	},
	{ emoji: '🌨️', name: 'cloud with snow', tags: ['snow', 'winter', 'cold', 'weather'] },
	{ emoji: '❄️', name: 'snowflake', tags: ['snow', 'winter', 'cold', 'ice'] },
	{ emoji: '☃️', name: 'snowman', tags: ['snowman', 'winter', 'cold', 'fun'] },
	{ emoji: '🌬️', name: 'wind face', tags: ['wind', 'blow', 'breeze', 'air'] },
	{ emoji: '💧', name: 'droplet', tags: ['water', 'drop', 'liquid', 'wet'] },
	{ emoji: '🌊', name: 'water wave', tags: ['wave', 'ocean', 'sea', 'surf'] },
	{ emoji: '🔥', name: 'fire', tags: ['fire', 'hot', 'flame', 'burn'] },
	{ emoji: '🌪️', name: 'tornado', tags: ['tornado', 'cyclone', 'storm', 'wind'] },
	{ emoji: '🌻', name: 'sunflower', tags: ['sunflower', 'flower', 'yellow', 'nature'] },
	{ emoji: '🌼', name: 'blossom', tags: ['flower', 'blossom', 'spring', 'nature'] },
	{ emoji: '🌸', name: 'cherry blossom', tags: ['cherry', 'blossom', 'pink', 'japan'] },
	{ emoji: '🌺', name: 'hibiscus', tags: ['hibiscus', 'flower', 'tropical', 'red'] },
	{ emoji: '🌹', name: 'rose', tags: ['rose', 'flower', 'love', 'red'] },
	{ emoji: '🌷', name: 'tulip', tags: ['tulip', 'flower', 'spring', 'netherlands'] },
	{ emoji: '🌱', name: 'seedling', tags: ['plant', 'grow', 'green', 'sprout'] },
	{ emoji: '🌿', name: 'herb', tags: ['herb', 'plant', 'green', 'nature'] },
	{ emoji: '☘️', name: 'shamrock', tags: ['shamrock', 'luck', 'irish', 'clover'] },
	{ emoji: '🍀', name: 'four leaf clover', tags: ['clover', 'luck', 'lucky', 'rare'] }
];
